name: Semgrep SAST

on:
  push:
    branches: ["master"]

jobs:
  semgrep:
    name: Scan Source Code
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Semgrep Scan
        run: semgrep scan --config auto
